name: bioinformatics
channels:
  - conda-forge
  - pkgs/main
dependencies:
  - aicsimageio=4.10.0=pyhd8ed1ab_0
  - aicspylibczi=3.3.1=py312hbb81ca0_2
  - aiodns=3.5.0=py312haa95532_1
  - aiohappyeyeballs=2.6.1=py312haa95532_0
  - aiohttp=3.13.3=py312h02ab6af_0
  - aiosignal=1.4.0=py312haa95532_0
  - annotated-types=0.6.0=py312haa95532_1
  - aom=3.12.1=h00a0c3c_0
  - arrow-cpp=19.0.0=h314dc4b_3
  - asttokens=3.0.0=py312haa95532_0
  - attrs=25.4.0=py312haa95532_2
  - aws-c-auth=0.8.5=h827c3e9_0
  - aws-c-cal=0.8.5=h827c3e9_0
  - aws-c-common=0.11.1=h827c3e9_0
  - aws-c-compression=0.3.1=h827c3e9_0
  - aws-c-event-stream=0.5.4=h5da7b33_0
  - aws-c-http=0.9.3=h827c3e9_0
  - aws-c-io=0.17.0=h827c3e9_0
  - aws-c-mqtt=0.12.2=h827c3e9_0
  - aws-c-s3=0.7.11=h827c3e9_0
  - aws-c-sdkutils=0.2.3=h827c3e9_0
  - aws-checksums=0.2.3=h827c3e9_0
  - aws-crt-cpp=0.31.0=h5da7b33_0
  - aws-sdk-cpp=1.11.528=h6a15179_0
  - blas=1.0=mkl
  - blosc=1.21.6=h4190f5b_0
  - bokeh=3.8.2=py312haa95532_0
  - boost-cpp=1.82.0=h59b6b97_2
  - bottleneck=1.4.2=py312h540bb41_1
  - brotli=1.0.9=h827c3e9_9
  - brotli-bin=1.0.9=h827c3e9_9
  - brotlicffi=1.2.0.0=py312h885b0b7_0
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.5=h731ff69_0
  - ca-certificates=2025.2.25=haa95532_0
  - cairo=1.18.4=he9e932c_0
  - certifi=2026.01.04=py312haa95532_0
  - cffi=2.0.0=py312h02ab6af_1
  - cfitsio=4.6.2=hfb9fb57_0
  - charls=2.4.2=h2e0806f_0
  - charset-normalizer=3.4.4=py312haa95532_0
  - click=8.2.1=py312haa95532_1
  - click-default-group=1.2.2=py312haa95532_0
  - cloudpickle=3.1.2=py312haa95532_0
  - colorama=0.4.6=py312haa95532_0
  - comm=0.2.3=py312haa95532_0
  - contourpy=1.3.3=py312h214f63a_0
  - crc32c=2.7.1=py312h827c3e9_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dask=2025.11.0=py312haa95532_1
  - dask-core=2025.11.0=py312haa95532_1
  - dav1d=1.2.1=h2bbff1b_0
  - debugpy=1.8.11=py312h5da7b33_0
  - decorator=5.2.1=py312haa95532_0
  - distributed=2025.11.0=py312haa95532_1
  - docformatter=1.7.7=pyhd8ed1ab_0
  - donfig=0.8.1.post1=py312haa95532_0
  - elementpath=5.0.4=py312haa95532_0
  - executing=2.2.1=py312haa95532_0
  - expat=2.7.1=h8ddb27b_0
  - ffmpeg=6.1.1=hc79a5da_3
  - flexcache=0.3=pyhd8ed1ab_1
  - flexparser=0.4=pyhd8ed1ab_1
  - fontconfig=2.15.0=hd211d86_0
  - fonttools=4.60.1=py312h02ab6af_0
  - freeglut=3.8.0=hfcef157_0
  - freetype=2.13.3=h0620614_0
  - fribidi=1.0.10=h62dcd97_0
  - frozenlist=1.8.0=py312h885b0b7_0
  - fsspec=2025.12.0=py312h4442805_0
  - gflags=2.2.2=hd77b12b_1
  - giflib=5.2.2=h7edc060_0
  - glog=0.5.0=hd77b12b_1
  - graphite2=1.3.14=hd77b12b_1
  - harfbuzz=10.2.0=he2f9f60_1
  - heapdict=1.0.1=pyhd3eb1b0_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.11=py312haa95532_0
  - imagecodecs=2024.9.22=py312h562091b_3
  - imageio=2.37.2=py312h4442805_0
  - imageio-ffmpeg=0.6.0=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=py312haa95532_0
  - intel-openmp=2025.0.0=haa95532_1164
  - ipykernel=6.31.0=py312h4442805_0
  - ipython=9.7.0=py312haa95532_0
  - ipython_pygments_lexers=1.1.1=py312haa95532_0
  - jedi=0.19.2=py312haa95532_0
  - jinja2=3.1.6=py312haa95532_0
  - joblib=1.5.3=py312haa95532_0
  - jpeg=9f=ha349fce_0
  - jupyter_client=8.6.3=py312haa95532_1
  - jupyter_core=5.9.1=py312haa95532_0
  - kiwisolver=1.4.9=py312h03f52e7_0
  - krb5=1.21.3=h885b0b7_4
  - lazy_loader=0.4=py312haa95532_0
  - lcms2=2.17=h3732fa5_0
  - lerc=4.0.0=h5da7b33_0
  - libabseil=20250127.0=cxx17_h52369b4_0
  - libaec=1.1.3=hcdb6601_0
  - libavif=1.3.0=h5bd13ec_0
  - libboost=1.82.0=h3399ecb_2
  - libbrotlicommon=1.0.9=h827c3e9_9
  - libbrotlidec=1.0.9=h827c3e9_9
  - libbrotlienc=1.0.9=h827c3e9_9
  - libcurl=8.17.0=h97e0424_0
  - libdeflate=1.22=h5bf469e_0
  - libevent=2.1.12=h56d1f94_1
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.4=hfaec014_0
  - libgrpc=1.71.0=hf4237ab_0
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.16=h2bbff1b_3
  - libkrb5=1.21.3=h885b0b7_4
  - libogg=1.3.5=h2bbff1b_1
  - libopenjpeg=2.5.4=h02ab6af_1
  - libpng=1.6.50=h46444df_0
  - libpq=17.4=h4a159e6_1
  - libprotobuf=5.29.3=h65a231f_1
  - libre2-11=2024.07.02=h5da7b33_0
  - libsodium=1.0.18=h62dcd97_0
  - libssh2=1.11.1=h2addb87_0
  - libtheora=1.1.1=h8cc25b3_3
  - libthrift=0.15.0=h4364b78_2
  - libtiff=4.7.1=h3a18249_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp-base=1.6.0=hbf3958f_0
  - libxml2=2.13.9=h6201b9f_0
  - libxslt=1.1.43=hd1fac9c_0
  - libzopfli=1.0.3=ha925a31_0
  - locket=1.0.0=py312haa95532_0
  - lxml=5.3.0=py312h985e36a_2
  - lz4=4.4.5=py312hb1efef3_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markdown-it-py=4.0.0=py312haa95532_1
  - markupsafe=3.0.2=py312h827c3e9_0
  - matplotlib=3.10.8=py312haa95532_0
  - matplotlib-base=3.10.8=py312h26e45b9_0
  - matplotlib-inline=0.2.1=py312haa95532_0
  - mdurl=0.1.2=py312haa95532_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py312h0b37514_0
  - mkl_fft=2.1.1=py312h300f80d_0
  - mkl_random=1.3.0=py312ha5e6156_0
  - msgpack-python=1.1.1=py312h5da7b33_0
  - multidict=6.7.0=py312h02ab6af_0
  - narwhals=2.7.0=py312haa95532_0
  - nest-asyncio=1.6.0=py312haa95532_0
  - networkx=3.6.1=py312haa95532_0
  - numcodecs=0.14.1=py312h4fc1ca9_0
  - numexpr=2.14.1=py312h7660c64_0
  - numpy=2.3.5=py312h050da96_0
  - numpy-base=2.3.5=py312h1e017a8_0
  - ome-types=0.6.3=pyhcf101f3_1
  - ome-zarr=0.12.2=pyhd8ed1ab_1
  - openjpeg=2.5.4=h56d5a42_1
  - openssl=3.0.16=h3f729d1_0
  - orc=2.1.1=hd1c1d5c_0
  - packaging=25.0=py312haa95532_1
  - pandas=2.2.2=py312h72972c8_1
  - parso=0.8.5=py312haa95532_0
  - partd=1.4.2=py312haa95532_0
  - pcre2=10.46=h5740b90_0
  - pillow=12.0.0=py312h4212202_1
  - pint=0.25.2=pyhcf101f3_0
  - pip=25.1=pyhc872135_2
  - pixman=0.46.4=h4043f72_0
  - platformdirs=4.5.0=py312haa95532_0
  - prompt-toolkit=3.0.52=py312haa95532_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - propcache=0.4.1=py312h02ab6af_0
  - psutil=5.9.0=py312h827c3e9_1
  - pure_eval=0.2.3=py312haa95532_0
  - pyarrow=19.0.0=py312h885b0b7_2
  - pycares=4.10.0=py312he29e43d_0
  - pycparser=2.23=py312haa95532_0
  - pydantic=2.12.4=py312haa95532_0
  - pydantic-core=2.41.5=py312h114bc41_1
  - pydantic-extra-types=2.10.5=py312haa95532_0
  - pygments=2.19.2=py312haa95532_0
  - pyparsing=3.2.5=py312haa95532_0
  - pyqt=6.7.1=py312h378bd72_2
  - pyqt6-sip=13.9.1=py312h02ab6af_2
  - pysocks=1.7.1=py312haa95532_1
  - python=3.12.11=h716150d_0
  - python-dateutil=2.9.0post0=py312haa95532_2
  - python-lmdb=1.7.5=py312h5823743_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.12=3_cp312
  - pytz=2025.2=py312haa95532_0
  - pywin32=308=py312h5da7b33_0
  - pyyaml=6.0.3=py312hb9a58be_0
  - pyzmq=26.2.0=py312h5da7b33_0
  - qtbase=6.7.3=hd088775_2
  - qtdeclarative=6.7.3=h885b0b7_1
  - qtsvg=6.7.3=h9d4b640_1
  - qttools=6.7.3=hcb596f7_1
  - qtwebchannel=6.7.3=h885b0b7_1
  - qtwebsockets=6.7.3=h885b0b7_1
  - re2=2024.07.02=h214f63a_0
  - requests=2.32.5=py312haa95532_1
  - resource_backed_dask_array=0.1.0=pyhd8ed1ab_1
  - rich=14.2.0=py312haa95532_0
  - ruff=0.12.0=py312h1361809_0
  - scikit-image=0.25.2=py312h42c1672_1
  - scikit-learn=1.8.0=py312h7f7e138_0
  - scipy=1.16.3=py312hbd6d557_0
  - seaborn=0.13.2=py312haa95532_3
  - setuptools=78.1.1=py312haa95532_0
  - shellingham=1.5.4=py312haa95532_0
  - sip=6.10.0=py312h5da7b33_0
  - six=1.17.0=py312haa95532_0
  - snappy=1.2.2=hab6b7b3_1
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.6.3=py312haa95532_0
  - tbb=2022.3.0=h90c84d6_0
  - tbb-devel=2022.3.0=h90c84d6_0
  - tblib=3.1.0=py312haa95532_0
  - threadpoolctl=3.5.0=py312h4442805_1
  - tifffile=2023.2.28=pyhd8ed1ab_0
  - tk=8.6.14=h5e9d12e_1
  - toolz=1.1.0=py312haa95532_0
  - toposort=1.10=pyhd8ed1ab_1
  - tornado=6.5.1=py312h827c3e9_0
  - traitlets=5.14.3=py312haa95532_0
  - typer=0.20.0=py312haa95532_0
  - typer-slim=0.20.0=py312haa95532_0
  - typer-slim-standard=0.20.0=py312haa95532_0
  - typing-extensions=4.15.0=py312haa95532_0
  - typing-inspection=0.4.2=py312haa95532_0
  - typing_extensions=4.15.0=py312haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - untokenize=0.1.1=pyhcf101f3_3
  - urllib3=2.6.3=py312haa95532_0
  - utf8proc=2.6.1=h2bbff1b_1
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.13=py312haa95532_0
  - wheel=0.45.1=py312haa95532_0
  - win_inet_pton=1.1.0=py312haa95532_1
  - winloop=0.3.1=py312h913537a_0
  - wrapt=2.0.1=py312h02ab6af_0
  - xarray=2025.12.0=py312haa95532_0
  - xmlschema=4.3.0=pyhd8ed1ab_0
  - xsdata=25.7=pyhd8ed1ab_0
  - xyzservices=2025.4.0=py312haa95532_0
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - yarl=1.22.0=py312h02ab6af_0
  - zarr=3.1.3=py312haa95532_0
  - zeromq=4.3.5=hd77b12b_0
  - zfp=1.0.1=hcfc1624_0
  - zict=3.0.0=py312haa95532_1
  - zipp=3.23.0=py312haa95532_0
  - zlib=1.2.13=h8cc25b3_1
  - zlib-ng=2.0.7=h2bbff1b_0
  - zstd=1.5.6=h8880b57_0
  - pip:
    - uv==0.9.17

prefix: "C:\\Users\\""\\miniforge3\\envs\\bioinformatics"
